### ISSUE TITLE
Huge icon in Switcher and Recent Files

### ISSUE THREAD

**Issue by rweisleder** [xdev-software/intellij-plugin-openrewriter#19]
When opening the "Switcher" (Ctrl + Tab) or "Recent Files" (Ctrl + E), the plugin icon is really huge. It should have the same size as the other icons.

![image](https://github.com/xdev-software/intellij-plugin-openrewriter/assets/1654369/b7568e6a-da77-408a-9acd-1950e8f5659e)

**Comment by AB-xdev** [comment]
Thank you for the issue

I tried to reproduce it, but was unable to do so:
![g](https://github.com/xdev-software/intellij-plugin-openrewriter/assets/45384811/1132f800-bb17-4a66-a7e9-8b957f504eb8)
![g](https://github.com/xdev-software/intellij-plugin-openrewriter/assets/45384811/c31f8ff1-4837-4c5e-8aaa-25a3c915d086)

I'm using
* IDEA 2024.1 - latest version
* Windows 10
* Full HD/1080p display

What IDE (+version) are you using and what OS?
Do you have any special display settings? (e.g. 4k display with 200% scaling set inside the OS)

**Comment by rweisleder** [comment]
Nothing special so far:
* Windows 11
* 1080p display, 100% scaling
* IDEA 2024.1.2
* Zoom 100% in IDEA
* OpenRewriter X 1.0.0

**Comment by AB-xdev** [comment]
Retested again and it seems to be only a problem when using the "New UI" with the "old" UI everything works fine.

**Comment by AB-xdev** [comment]
The problem is not present on IDEA 2023.2 with the new UI, so there must have been a change in newer versions of IDEA...

**Comment by AB-xdev** [comment]
There seems to be a problem inside:
https://github.com/JetBrains/intellij-community/blob/def6433a5dd9f0a984cbc6e2835d27c97f2cb5f0/platform/platform-impl/src/com/intellij/ide/actions/SwitcherRendering.kt#L113-L119

* Due to some reason the icon width of our SVG pluginIcon in ``window.icon`` is always 13 (even when I set width="512" or something similar explicitly)
* The New UI uses 16x16 (instead of 13x13) as reference scale
* This causes the scaleByIcon Function to be invoke and trying to scale the icon, which goes completely wrong
  * It seems to work in the following way 16 (reference width)/13 (incorrect detected width) * 512 (actual width), which results in 630

**Comment by AB-xdev** [comment]
The only difference between 2023.2 and 2024-EAP seems to be that in
2023.2 ``window.icon`` is a ``ToolWindowIcon`` while in 2024-EAP it's a ``CachedImageIcon``, which seems to result in the different scaling.

**Comment by AB-xdev** [comment]
Reported to JetBrains via https://youtrack.jetbrains.com/issue/IDEA-354465

**Comment by rweisleder** [comment]
Thanks for analyzing and reporting!

**Comment by AB-xdev** [comment]
As a workaround I set the (default) width and height of the pluginIcon to 16px, this should workaround the bug until a fix is provided.

**Comment by AB-xdev** [comment]
Closed here and handed over to https://github.com/xdev-software/intellij-plugin-template/issues/26 for further tracking.
